AWSTemplateFormatVersion: '2010-09-09'
Description: Symfony Demo App

Resources:
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apis
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::381375271776:role/ecs-ECSRole-eu-west-1
      ContainerDefinitions:
        - Name: symfony-demo
          Image: 381375271776.dkr.ecr.eu-west-1.amazonaws.com/symfony-demo:v1
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 4567
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'apis'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'symfony-demo'

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: books-service
      TaskDefinition: !Ref Task
      Cluster: 'ecs'
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-017275048f9e5c6cd
            - subnet-0b89bc5727b3ccc40
          SecurityGroups:
            - 'sg-0d651168521a746c8'
      LoadBalancers:
        - ContainerName: symfony-demo
          ContainerPort: 4567
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: books-tg
      VpcId: vpc-067a93d13b158ee71
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue 'Listener'
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  ApiEndpoint:
    Description: Symfony Demo App Endpoint
    Value: !Join ['', ['http://', !ImportValue 'DomainName', '/']]
    Export:
      Name: 'SymfonyDemoAppEndpoint'